from __future__ import annotations

from typing import Any, Callable, Iterable, Protocol


class DatabaseGateway(Protocol):
    """Small persistence contract shared by SQLite and MySQL adapters."""

    def execute(self, sql: str, params: Iterable[Any] = ()) -> int: ...
    def executemany(self, sql: str, params: Iterable[Iterable[Any]]) -> int: ...
    def query(self, sql: str, params: Iterable[Any] = ()) -> list[Any]: ...
    def query_one(self, sql: str, params: Iterable[Any] = ()) -> Any | None: ...
    def transaction(self, callback: Callable[[Any], Any]) -> Any: ...
    def account_balance(self, account_id: int) -> float: ...
    def account_balances(self) -> list[Any]: ...
