const app = document.querySelector('#app');
let token = sessionStorage.token || '';
let me = null;
let lookups = null;

const api = async (path, options = {}) => {
  const response = await fetch('/api' + path, {
    ...options,
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) },
  });
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || 'The request could not be completed.');
  return response.status === 204 ? null : response.json();
};
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const money = value => Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const humanTime = value => {
  const match = String(value ?? '').match(/(?:T|\s)(\d{1,2}):(\d{2})(?::\d{2})?$/);
  if (!match) return value || '';
  const hour = Number(match[1]);
  return `${((hour + 11) % 12) + 1}:${match[2]} ${hour >= 12 ? 'PM' : 'AM'}`;
};
const has = permission => me?.permissions?.includes(permission);

function showError(error) { alert(error?.message || String(error)); }
function table(rows, columns) {
  const body = rows.length ? rows.map(row => `<tr>${columns.map(column => `<td>${column.render ? column.render(row) : esc(row[column.key])}</td>`).join('')}</tr>`).join('') : `<tr><td class="empty" colspan="${columns.length}">No records found.</td></tr>`;
  return `<div class="table-wrap"><table><thead><tr>${columns.map(column => `<th>${esc(column.label)}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;
}
function toolbar(actions = [], hint = '') { return `<div class="toolbar">${actions.join('')} ${hint ? `<span class="muted">${hint}</span>` : ''}</div>`; }
function action(label, onclick, primary = false) { return `<button class="${primary ? 'primary' : ''}" onclick="${onclick}">${esc(label)}</button>`; }
function modal(title, content) {
  const host = document.createElement('div'); host.className = 'modal';
  host.innerHTML = `<section class="panel modal-panel"><div class="modal-title"><h2>${esc(title)}</h2><button class="icon-btn" aria-label="Close">×</button></div>${content}</section>`;
  host.onclick = event => { if (event.target === host) host.remove(); };
  host.querySelector('.icon-btn').onclick = () => host.remove();
  document.body.append(host); return host;
}
function formData(form) { return Object.fromEntries(new FormData(form)); }
function selectOptions(rows, valueKey, label) { return rows.map(row => `<option value="${esc(row[valueKey])}">${esc(label(row))}</option>`).join(''); }
async function getLookups() { if (!lookups) lookups = await api('/lookups'); return lookups; }

const navGroups = [
  ['Operations', [['dashboard', 'Dashboard', 'dashboard.view'], ['attendance', 'Attendance', 'devices.manage'], ['tasks', 'Tasks & Bugs', 'dashboard.view'], ['reports', 'Reports', 'reports.view']]],
  ['Academic', [['students', 'Students', 'students.manage'], ['enrollments', 'Enrollments', 'enrollments.manage'], ['bills', 'Due Bills & Payments', 'billing.manage'], ['courses', 'Courses', 'master_data.manage'], ['schools', 'Schools', 'master_data.manage']]],
  ['People & Finance', [['staff', 'Staff', 'staff.manage'], ['finance', 'Finance', 'finance.manage'], ['transfers', 'Account Transfers', 'finance.manage']]],
  ['Administration', [['company', 'Company Details', 'administration.manage']]],
];
function shell(title, subtitle, body) {
  const active = location.hash.slice(1) || 'dashboard';
  const navigation = navGroups.map(([group, pages]) => {
    const visible = pages.filter(([, , permission]) => has(permission));
    if (!visible.length) return '';
    return `<div class="nav-group"><div class="nav-group-title">${esc(group)}</div>${visible.map(([page, label]) => `<button class="nav ${active === page ? 'active' : ''}" onclick="go('${page}')">${esc(label)}</button>`).join('')}</div>`;
  }).join('');
  app.innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand"><span>ELH</span> WEB</div>${navigation}<div class="sidebar-bottom"><button class="nav" onclick="logout()">Sign out</button></div></aside><main class="content"><header class="top"><div><h1>${esc(title)}</h1><p class="muted">${esc(subtitle)}</p></div><div class="user">${esc(me?.display_name || '')}<small>${esc(me?.role || '')}</small></div></header>${body}</main></div>`;
}
function csvDownload(filename, rows, columns) {
  const output = [columns.map(c => c.label), ...rows.map(row => columns.map(c => c.csv ? c.csv(row) : (c.render ? '' : row[c.key] ?? '')))];
  const text = output.map(row => row.map(value => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n');
  const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type: 'text/csv' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href);
}

async function dashboard() {
  const data = await api('/dashboard');
  shell('Dashboard', 'Today’s operational overview', `<div class="cards">${[['Students', data.metrics.students], ['Active staff', data.metrics.staff], ['Active enrollments', data.metrics.enrollments], ['Outstanding', money(data.metrics.outstanding)]].map(([label, value]) => `<div class="card"><span>${label}</span><b>${value}</b></div>`).join('')}</div><section class="panel"><h2>Students present today</h2>${table(data.present_today, [{ key: 'student_name', label: 'Student' }, { key: 'class_name', label: 'Class' }, { key: 'punches', label: 'Punches' }, { key: 'first_seen', label: 'First punch', render: row => humanTime(row.first_seen) }, { key: 'last_seen', label: 'Last punch', render: row => humanTime(row.last_seen) }])}</section><section class="panel"><h2>Attendance follow-up</h2>${table(data.attendance_alerts, [{ key: 'student_name', label: 'Student' }, { key: 'class_name', label: 'Class' }, { key: 'reason', label: 'Reason' }, { key: 'review_status', label: 'Status' }])}</section>`);
}

const studentColumns = [{ key: 'id', label: 'ID' }, { key: 'student_name', label: 'Student' }, { key: 'class_name', label: 'Class' }, { key: 'school_name', label: 'School' }, { key: 'contact', label: 'Contact' }, { key: 'enrolled', label: 'Enrolled', render: row => row.enrolled ? 'Yes' : 'No' }, { key: 'status', label: 'Status' }, { key: 'actions', label: '', render: row => `<button onclick="editStudent(${row.id})">Edit</button>` }];
async function students() {
  const rows = await api('/students');
  shell('Students', 'Records, attendance identity, and enrollment status', `${toolbar([`<input id="studentSearch" placeholder="Search students" oninput="filterStudents()">`, `<select id="studentStatus" onchange="filterStudents()"><option>All</option><option>Active</option><option>Inactive</option></select>`, action('Add student', 'studentForm()', true), action('Export visible CSV', 'exportStudentCsv()')])}<div id="studentTable">${table(rows, studentColumns)}</div>`);
  window._students = rows;
}
async function filterStudents() { const query = document.querySelector('#studentSearch').value; const status = document.querySelector('#studentStatus').value; const rows = await api(`/students?query=${encodeURIComponent(query)}&status=${status}`); window._students = rows; document.querySelector('#studentTable').innerHTML = table(rows, studentColumns); }
function exportStudentCsv() { csvDownload('students.csv', window._students || [], studentColumns.slice(0, -1)); }
async function studentForm(existing = null) {
  const data = await getLookups(); const value = key => esc(existing?.[key] || '');
  const schoolOptions = `<option value="">Not assigned</option>${data.schools.map(s => `<option value="${s.id}" ${existing?.school_id === s.id ? 'selected' : ''}>${esc(s.school_name)}</option>`).join('')}`;
  const classOptions = `<option value="">Not assigned</option>${data.classes.map(c => `<option ${existing?.class_name === c.level_name ? 'selected' : ''}>${esc(c.level_name)}</option>`).join('')}`;
  const host = modal(existing ? 'Edit student' : 'Add student', `<form class="form two-col"><label>Name *<input name="name" required value="${value('name')}"></label><label>Class<select name="class_name">${classOptions}</select></label><label>School<select name="school_id">${schoolOptions}</select></label><label>Contact<input name="contact" value="${value('contact')}"></label><label>Gender<select name="gender"><option></option>${['Male','Female','Other'].map(v => `<option ${existing?.gender === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Joining date (BS) *<input name="joining_date" required placeholder="2083/05/10" value="${value('joining_date')}"></label><label>Date of birth (BS)<input name="date_of_birth" value="${value('date_of_birth')}"></label><label>Parent / Guardian<input name="parent_name" value="${value('parent_name')}"></label><label>Relationship<input name="guardian_relationship" value="${value('guardian_relationship')}"></label><label>Status<select name="status">${['Active','Inactive'].map(v => `<option ${(!existing && v === 'Active') || existing?.status === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label class="span-2">Address<input name="address" value="${value('address')}"></label><label class="span-2">Remarks<input name="remarks" value="${value('remarks')}"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">${existing ? 'Save changes' : 'Save student'}</button>${existing ? `<button type="button" class="danger" onclick="archiveStudent(${existing.id})">Archive</button>` : ''}</div></form>`);
  host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.school_id = payload.school_id ? Number(payload.school_id) : null; try { await api(existing ? `/students/${existing.id}` : '/students', { method: existing ? 'PUT' : 'POST', body: JSON.stringify(payload) }); lookups = null; host.remove(); go('students'); } catch (error) { showError(error); } };
}
async function editStudent(id) { const record = await api(`/students/${id}`); studentForm(record); }
async function archiveStudent(id) { if (!confirm('Archive this student? Existing history will be retained.')) return; try { await api(`/students/${id}/archive`, { method: 'POST' }); document.querySelector('.modal')?.remove(); go('students'); } catch (error) { showError(error); } }

async function enrollments() {
  const rows = await api('/enrollments'); const columns = [{ key: 'id', label: 'ID' }, { key: 'student_name', label: 'Student' }, { key: 'course_name', label: 'Course' }, { key: 'level', label: 'Class' }, { key: 'start_date', label: 'Start' }, { key: 'end_date', label: 'End' }, { key: 'monthly_fee', label: 'Monthly fee', render: row => money(row.monthly_fee) }, { key: 'status', label: 'Status' }];
  shell('Enrollments', 'Assign students to courses and retain course history', `${toolbar([action('Assign enrollment', 'enrollmentForm()', true), action('Export CSV', 'exportEnrollments()')])}${table(rows, columns)}`); window._enrollments = rows; window._enrollmentColumns = columns;
}
function exportEnrollments() { csvDownload('enrollments.csv', window._enrollments || [], window._enrollmentColumns || []); }
async function enrollmentForm() {
  const [studentRows, courseRows] = await Promise.all([api('/students'), api('/courses')]);
  const host = modal('Assign enrollment', `<form class="form two-col"><label>Student *<select name="student_id">${selectOptions(studentRows, 'id', row => `${row.student_name}${row.class_name ? ` - ${row.class_name}` : ''}`)}</select></label><label>Course *<select name="course_id" onchange="this.form.monthly_fee.value=this.selectedOptions[0].dataset.fee">${courseRows.map(row => `<option value="${row.id}" data-fee="${row.default_fee || 0}">${esc(row.course_name)} (${esc(row.category)})</option>`).join('')}</select></label><label>Class / level<input name="level"></label><label>Start date (BS) *<input name="start_date" required placeholder="2083/05/10"></label><label>End date (BS)<input name="end_date"></label><label>Monthly fee<input name="monthly_fee" type="number" min="0" value="${courseRows[0]?.default_fee || 0}"></label><label>Admission fee<input name="admission_fee" type="number" min="0" value="0"></label><label>Discount<input name="discount" type="number" min="0" value="0"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save enrollment</button></div></form>`);
  host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); ['student_id','course_id'].forEach(k => payload[k] = Number(payload[k])); ['monthly_fee','admission_fee','discount'].forEach(k => payload[k] = Number(payload[k])); try { await api('/enrollments', { method: 'POST', body: JSON.stringify(payload) }); host.remove(); go('enrollments'); } catch (error) { showError(error); } };
}

async function bills() {
  const rows = await api('/bills'); const columns = [{ key: 'bill_number', label: 'Bill no.' }, { key: 'student_name', label: 'Student' }, { key: 'course_name', label: 'Course' }, { key: 'billing_period', label: 'Period' }, { key: 'due_date', label: 'Due date' }, { key: 'total_amount', label: 'Total', render: row => money(row.total_amount) }, { key: 'paid_amount', label: 'Paid', render: row => money(row.paid_amount) }, { key: 'balance', label: 'Balance', render: row => money(row.balance) }, { key: 'status', label: 'Status' }, { key: 'pay', label: '', render: row => row.balance > 0 ? `<button class="primary small" onclick="billPayment(${row.id})">Receive payment</button>` : '' }];
  shell('Due Bills & Payments', 'Generate bills, accept payments, and track balances', `${toolbar([action('Generate bills', 'billGenerationForm()', true), action('Export CSV', 'exportBills()')])}${table(rows, columns)}`); window._bills = rows; window._billColumns = columns;
}
function exportBills() { csvDownload('due-bills.csv', window._bills || [], (window._billColumns || []).slice(0, -1)); }
async function billGenerationForm() {
  const enrollmentsRows = await api('/enrollments');
  const host = modal('Generate due bills', `<form class="form two-col"><label class="span-2">Enrollments *<select name="enrollment_ids" multiple size="9">${enrollmentsRows.filter(row => row.status === 'Active').map(row => `<option value="${row.id}">${esc(row.student_name)} — ${esc(row.course_name)} (${esc(row.level || '')})</option>`).join('')}</select><small>Use Ctrl or Shift to select several enrollments.</small></label><label>Start month (BS) *<input name="start_month" placeholder="2083/05" required></label><label>End month (BS) *<input name="end_month" placeholder="2083/05" required></label><label>Issue date (BS) *<input name="issue_date" placeholder="2083/05/10" required></label><label>Due date (BS) *<input name="due_date" placeholder="2083/05/15" required></label><label class="span-2">Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Generate</button></div></form>`);
  host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.enrollment_ids = [...event.target.elements.enrollment_ids.selectedOptions].map(option => Number(option.value)); try { const result = await api('/bills/generate', { method: 'POST', body: JSON.stringify(payload) }); alert(`${result.created} bill(s) generated.`); host.remove(); go('bills'); } catch (error) { showError(error); } };
}
async function billPayment(id) {
  const data = await getLookups(); const bill = (window._bills || []).find(row => row.id === id); const host = modal(`Receive payment — ${bill?.bill_number || ''}`, `<form class="form two-col"><label>Payment amount *<input name="amount" type="number" min="0" step="0.01" value="${bill?.balance || 0}"></label><label>Discount<input name="discount" type="number" min="0" step="0.01" value="0"></label><label>Payment date (BS) *<input name="payment_date" placeholder="2083/05/10" required></label><label>Account *<select name="account_id"><option value="">Select account</option>${selectOptions(data.accounts, 'id', row => `${row.account_name} (${row.account_type})`)}</select></label><label>Method<select name="payment_method"><option>Cash</option><option>Bank</option><option>Wallet</option><option>Other</option></select></label><label>Receipt no.<input name="receipt_no"></label><label class="span-2">Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Receive payment</button></div></form>`);
  host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.amount = Number(payload.amount); payload.discount = Number(payload.discount); payload.account_id = payload.account_id ? Number(payload.account_id) : null; try { await api(`/bills/${id}/payment`, { method: 'POST', body: JSON.stringify(payload) }); host.remove(); go('bills'); } catch (error) { showError(error); } };
}

async function attendance() {
  const [absent, alerts, punched] = await Promise.all([api('/attendance/absent-today'), api('/attendance/alerts'), api('/attendance/punched-not-enrolled')]);
  shell('Attendance', 'Daily presence, manual corrections, and follow-up review', `${toolbar([action('Mark manual presence', 'manualAttendanceForm()', true), action('Show suppressed alerts', 'attendanceAlerts(true)')])}<section class="panel"><h2>Students absent today</h2>${table(absent, [{ key: 'student_name', label: 'Student' }, { key: 'class_name', label: 'Class' }, { key: 'courses', label: 'Course(s)' }, { key: 'last_seen', label: 'Last attendance', render: row => humanTime(row.last_seen) }, { key: 'device_status', label: 'Device' }])}</section><section class="panel"><h2>Attendance follow-up alerts</h2>${table(alerts, [{ key: 'student_name', label: 'Student' }, { key: 'class_name', label: 'Class' }, { key: 'reason', label: 'Reason' }, { key: 'review_status', label: 'Status' }, { key: 'review', label: '', render: row => `<button onclick="attendanceReviewForm(${row.student_id}, '${esc(row.student_name)}')">Review</button>` }])}</section><section class="panel"><h2>Punched but not enrolled</h2>${table(punched, [{ key: 'student_name', label: 'Student' }, { key: 'class_name', label: 'Class' }, { key: 'punches', label: 'Punches' }, { key: 'last_seen', label: 'Last punch', render: row => humanTime(row.last_seen) }])}</section>`);
}
async function attendanceAlerts(includeSuppressed) { const rows = await api(`/attendance/alerts?include_suppressed=${includeSuppressed}`); modal('Attendance follow-up alerts', table(rows, [{ key: 'student_name', label: 'Student' }, { key: 'reason', label: 'Reason' }, { key: 'review_status', label: 'Status' }, { key: 'follow_up_date', label: 'Resume date' }, { key: 'review_note', label: 'Note' }])); }
async function manualAttendanceForm() { const people = await api('/attendance/people'); const studentsRows = people.students; const staffRows = people.staff; const host = modal('Mark manual attendance', `<form class="form two-col"><label>Person type<select name="person_type" onchange="switchManualPeople(this.value)"><option value="student">Student</option><option value="teacher">Staff</option></select></label><label>Student / staff<select name="person_id" id="manualPerson">${selectOptions(studentsRows, 'id', row => row.student_name)}</select></label><label>Attendance date (BS) *<input name="attendance_date" placeholder="2083/05/10" required></label><label>Time *<input name="attendance_time" placeholder="6:00 PM" required></label><label class="span-2">Reason *<input name="reason" required value="Device attendance missed"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Mark present</button></div></form>`); window._manualPeople = { student: studentsRows.map(row => ({ id: row.id, label: row.student_name })), teacher: staffRows.map(row => ({ id: row.id, label: row.teacher_name })) }; host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.person_id = Number(payload.person_id); try { const result = await api('/attendance/manual', { method: 'POST', body: JSON.stringify(payload) }); alert(result.created ? 'Manual presence recorded.' : 'Attendance was already recorded for this person today.'); host.remove(); go('attendance'); } catch (error) { showError(error); } }; }
function switchManualPeople(type) { const select = document.querySelector('#manualPerson'); select.innerHTML = (window._manualPeople?.[type] || []).map(row => `<option value="${row.id}">${esc(row.label)}</option>`).join(''); }
function attendanceReviewForm(studentId, name) { const host = modal(`Review follow-up — ${name}`, `<form class="form"><label>Status<select name="status"><option>Monitoring</option><option>Contacted</option><option>Approved Leave</option><option>Left Institution</option><option>No Action Needed</option><option>Suppressed</option></select></label><label>Resume / follow-up date (BS)<input name="follow_up_date" placeholder="2083/06/01"></label><label>Notes<input name="note"></label><div class="form-actions"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save review</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); try { await api(`/attendance/alerts/${studentId}/review`, { method: 'POST', body: JSON.stringify(formData(event.target)) }); host.remove(); go('attendance'); } catch (error) { showError(error); } }; }

async function courses() { const rows = await api('/courses?include_inactive=true'); const cols = [{ key: 'course_name', label: 'Course' }, { key: 'category', label: 'Category' }, { key: 'billing_type', label: 'Billing' }, { key: 'default_fee', label: 'Fee', render: row => money(row.default_fee) }, { key: 'duration_months', label: 'Months' }, { key: 'instructor_name', label: 'Instructor' }, { key: 'status', label: 'Status' }]; shell('Courses', 'Reusable course definitions and billing defaults', `${toolbar([action('Add course', 'courseForm()', true), action('Export CSV', 'exportCourses()')])}${table(rows, cols)}`); window._courses = rows; window._courseCols = cols; }
function exportCourses() { csvDownload('courses.csv', window._courses || [], window._courseCols || []); }
function courseForm() { const host = modal('Add course', `<form class="form two-col"><label>Course name *<input name="course_name" required></label><label>Category *<input name="category" required value="Tuition"></label><label>Billing type<select name="billing_type"><option>Monthly</option><option>Course Complete</option></select></label><label>Default fee<input name="default_fee" type="number" min="0" value="0"></label><label>Duration months<input name="duration_months" type="number" min="0" value="0"></label><label>Instructor name<input name="instructor_name"></label><label>Status<select name="status"><option>Active</option><option>Inactive</option></select></label><label>Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save course</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.default_fee = Number(payload.default_fee); payload.duration_months = Number(payload.duration_months); try { await api('/courses', { method: 'POST', body: JSON.stringify(payload) }); host.remove(); go('courses'); } catch (error) { showError(error); } }; }
async function schools() { const rows = await api('/schools?include_inactive=true'); const cols = [{ key: 'school_name', label: 'School' }, { key: 'emis_id', label: 'EMIS ID' }, { key: 'address', label: 'Address' }, { key: 'contact', label: 'Contact' }, { key: 'status', label: 'Status' }]; shell('Schools', 'Schools linked to student records', `${toolbar([action('Add school', 'schoolForm()', true), action('Export CSV', 'exportSchools()')])}${table(rows, cols)}`); window._schools = rows; window._schoolCols = cols; }
function exportSchools() { csvDownload('schools.csv', window._schools || [], window._schoolCols || []); }
function schoolForm() { const host = modal('Add school', `<form class="form two-col"><label>School name *<input name="school_name" required></label><label>EMIS ID<input name="emis_id"></label><label>Contact<input name="contact"></label><label>Status<select name="status"><option>Active</option><option>Inactive</option></select></label><label class="span-2">Address<input name="address"></label><label class="span-2">Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save school</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); try { await api('/schools', { method: 'POST', body: JSON.stringify(formData(event.target)) }); lookups = null; host.remove(); go('schools'); } catch (error) { showError(error); } }; }

async function staff() { const rows = await api('/staff'); const cols = [{ key: 'teacher_name', label: 'Staff' }, { key: 'staff_type', label: 'Type' }, { key: 'contact', label: 'Contact' }, { key: 'subject', label: 'Subject' }, { key: 'salary_type', label: 'Salary basis' }, { key: 'basic_salary', label: 'Rate', render: row => money(row.basic_salary) }, { key: 'status', label: 'Status' }]; shell('Staff', 'Teaching and non-teaching staff with payment-account tracking', `${toolbar([action('Add staff', 'staffForm()', true), action('Export CSV', 'exportStaff()')])}${table(rows, cols)}`); window._staff = rows; window._staffCols = cols; }
function exportStaff() { csvDownload('staff.csv', window._staff || [], window._staffCols || []); }
function staffForm() { const host = modal('Add staff', `<form class="form two-col"><label>Name *<input name="teacher_name" required></label><label>Staff type<select name="staff_type"><option>Teaching</option><option>Non Teaching</option></select></label><label>Contact<input name="contact"></label><label>Email<input name="email"></label><label>Subject / role<input name="subject"></label><label>Qualification<input name="qualification"></label><label>Joined date (BS) *<input name="joined_date" placeholder="2083/05/10" required></label><label>Salary type<select name="salary_type"><option>Monthly Salary</option><option>Per Class Payment</option></select></label><label>Basic salary / rate<input name="basic_salary" type="number" min="0" value="0"></label><label>Status<select name="status"><option>Active</option><option>Inactive</option></select></label><label class="span-2">Address<input name="address"></label><label class="span-2">Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save staff</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.basic_salary = Number(payload.basic_salary); try { await api('/staff', { method: 'POST', body: JSON.stringify(payload) }); host.remove(); go('staff'); } catch (error) { showError(error); } }; }

async function finance() { const [accounts, incomeRows, expenseRows, ledgerRows] = await Promise.all([api('/accounts'), api('/income'), api('/expenses'), api('/ledger')]); shell('Finance', 'Accounts, income, expenses, and current ledger', `${toolbar([action('Add account', 'accountForm()', true), action('Record income', 'moneyForm("income")'), action('Record expense', 'moneyForm("expenses")')])}<section class="panel"><h2>Accounts</h2>${table(accounts, [{ key: 'account_name', label: 'Account' }, { key: 'account_type', label: 'Type' }, { key: 'balance', label: 'Current balance', render: row => money(row.balance) }, { key: 'status', label: 'Status' }])}</section><section class="panel"><h2>Income</h2>${table(incomeRows, [{ key: 'income_date', label: 'Date' }, { key: 'category', label: 'Category' }, { key: 'particular', label: 'Particular' }, { key: 'amount', label: 'Amount', render: row => money(row.amount) }, { key: 'account_name', label: 'Account' }])}</section><section class="panel"><h2>Expenses</h2>${table(expenseRows, [{ key: 'expense_date', label: 'Date' }, { key: 'category', label: 'Category' }, { key: 'particular', label: 'Particular' }, { key: 'amount', label: 'Amount', render: row => money(row.amount) }, { key: 'account_name', label: 'Account' }, { key: 'payee_name', label: 'Payee' }])}</section><section class="panel"><h2>Ledger</h2>${table(ledgerRows, [{ key: 'transaction_date', label: 'Date' }, { key: 'account_name', label: 'Account' }, { key: 'direction', label: 'Direction' }, { key: 'amount', label: 'Amount', render: row => money(row.amount) }, { key: 'particular', label: 'Particular' }, { key: 'reference_no', label: 'Reference' }])}</section>`); }
function accountForm() { const host = modal('Add account', `<form class="form two-col"><label>Account name *<input name="account_name" required></label><label>Type<select name="account_type"><option>Cash Counter</option><option>Bank Account</option><option>Personal Account</option><option>Wallet</option><option>Other</option></select></label><label>Bank name<input name="bank_name"></label><label>Account no.<input name="account_number"></label><label>Account holder<input name="account_holder"></label><label>Opening balance<input name="opening_balance" type="number" value="0"></label><label>Status<select name="status"><option>Active</option><option>Inactive</option></select></label><label>Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save account</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.opening_balance = Number(payload.opening_balance); try { await api('/accounts', { method: 'POST', body: JSON.stringify(payload) }); lookups = null; host.remove(); go('finance'); } catch (error) { showError(error); } }; }
async function moneyForm(type) { const data = await getLookups(); const heading = type === 'income' ? 'Record income' : 'Record expense'; const host = modal(heading, `<form class="form two-col"><label>Date (BS) *<input name="record_date" placeholder="2083/05/10" required></label><label>Category *<input name="category" required></label><label class="span-2">Particular *<input name="particular" required></label><label>Amount *<input name="amount" type="number" min="0.01" step="0.01" required></label><label>${type === 'income' ? 'Received in account' : 'Paid from account'} *<select name="account_id">${selectOptions(data.accounts, 'id', row => row.account_name)}</select></label><label>${type === 'income' ? 'Received from' : 'Paid to'}<input name="party"></label><label>Payment method<select name="payment_method"><option>Cash</option><option>Bank</option><option>Wallet</option><option>Other</option></select></label><label>Reference no.<input name="reference_no"></label><label>Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save ${type}</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.amount = Number(payload.amount); payload.account_id = Number(payload.account_id); try { await api(`/${type}`, { method: 'POST', body: JSON.stringify(payload) }); host.remove(); go('finance'); } catch (error) { showError(error); } }; }

async function tasks() { const [taskRows, bugRows] = await Promise.all([api('/tasks'), api('/bug-reports')]); const taskCols = [{key:'title',label:'Task'}, {key:'assigned_to',label:'Assigned to'}, {key:'due_date',label:'Due date'}, {key:'priority',label:'Priority'}, {key:'status',label:'Status'}, {key:'done',label:'',render: row => row.status === 'Done' ? '' : `<button onclick="completeTask(${row.id})">Mark done</button>`}]; const bugCols = [{key:'title',label:'Issue'}, {key:'page_name',label:'Screen'}, {key:'severity',label:'Severity'}, {key:'status',label:'Status'}, {key:'reported_by',label:'Reported by'}, {key:'created_at',label:'Reported'}]; shell('Tasks & Bugs', 'Assign follow-ups to staff and maintain a clear issue register', `${toolbar([action('New task','taskForm()',true),action('Report a bug','bugForm()')])}<section class="panel"><h2>Tasks</h2>${table(taskRows, taskCols)}</section><section class="panel"><h2>Bug reports</h2>${table(bugRows, bugCols)}</section>`); }
async function taskForm() { const people = await api('/attendance/people'); const host = modal('New task', `<form class="form two-col"><label class="span-2">Task *<input name="title" required></label><label>Assign to staff<select name="assigned_teacher_id"><option value="">Unassigned</option>${selectOptions(people.staff,'id',row=>row.teacher_name)}</select></label><label>Due date (BS)<input name="due_date" placeholder="2083/05/10"></label><label>Priority<select name="priority"><option>Low</option><option selected>Normal</option><option>High</option></select></label><label class="span-2">Details<input name="details"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Save task</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); payload.assigned_teacher_id = payload.assigned_teacher_id ? Number(payload.assigned_teacher_id) : null; try { await api('/tasks',{method:'POST',body:JSON.stringify(payload)}); host.remove(); go('tasks'); } catch(error) { showError(error); } }; }
async function completeTask(id) { try { await api(`/tasks/${id}/complete`,{method:'POST'}); go('tasks'); } catch(error) { showError(error); } }
function bugForm() { const host = modal('Report a bug', `<form class="form"><label>What happened? *<input name="title" required></label><label>Screen / page<input name="page_name" value="${esc(location.hash.slice(1) || 'dashboard')}"></label><label>Severity<select name="severity"><option>Low</option><option selected>Normal</option><option>High</option><option>Critical</option></select></label><label>Details / steps to repeat *<textarea name="details" required rows="5"></textarea></label><div class="form-actions"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Submit report</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); try { await api('/bug-reports',{method:'POST',body:JSON.stringify(formData(event.target))}); host.remove(); alert('Bug report saved for follow-up.'); go('tasks'); } catch(error) { showError(error); } }; }
async function transfers() { const rows = await api('/transfers'); const cols = [{key:'transfer_date',label:'Date'}, {key:'from_account',label:'From'}, {key:'to_account',label:'To'}, {key:'amount',label:'Amount',render:row=>money(row.amount)}, {key:'transfer_charge',label:'Charge',render:row=>money(row.transfer_charge)}, {key:'reference_no',label:'Reference'}]; shell('Account Transfers','Move money safely between institution accounts',`${toolbar([action('New transfer','transferForm()',true)])}${table(rows,cols)}`); }
async function transferForm() { const data = await getLookups(); const options = `<option value="">Select account</option>${selectOptions(data.accounts,'id',row=>`${row.account_name} (${row.account_type})`)}`; const host = modal('Transfer between accounts', `<form class="form two-col"><label>Date (BS) *<input name="transfer_date" placeholder="2083/05/10" required></label><label>Amount *<input name="amount" type="number" min="0.01" step="0.01" required></label><label>From account *<select name="from_account_id" required>${options}</select></label><label>To account *<select name="to_account_id" required>${options}</select></label><label>Transfer charge<input name="transfer_charge" type="number" min="0" step="0.01" value="0"></label><label>Reference no.<input name="reference_no"></label><label class="span-2">Remarks<input name="remarks"></label><div class="form-actions span-2"><button type="button" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary">Transfer money</button></div></form>`); host.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = formData(event.target); ['from_account_id','to_account_id'].forEach(key=>payload[key]=Number(payload[key])); ['amount','transfer_charge'].forEach(key=>payload[key]=Number(payload[key])); try { await api('/transfers',{method:'POST',body:JSON.stringify(payload)}); host.remove(); lookups=null; go('transfers'); } catch(error) { showError(error); } }; }
async function reports() { shell('Reports', 'Export any operational table to CSV or print the current view from your browser', `<section class="panel"><h2>Operational reports</h2><p>Use the Export CSV action in Students, Enrollments, Due Bills, Courses, Schools, and Staff to download the current operational data. Use your browser’s Print command for a paper/PDF copy of the current view.</p>${toolbar([action('Print this page', 'window.print()', true)])}</section>`); }
async function company() { const data = await api('/company-profile'); const html = `<form id="companyForm" class="form two-col"><label>Company name *<input name="company_name" required value="${esc(data.company_name || '')}"></label><label>PAN no.<input name="pan_number" value="${esc(data.pan_number || '')}"></label><label>Registration no.<input name="registration_number" value="${esc(data.registration_number || '')}"></label><label>Principal / Director<input name="principal_name" value="${esc(data.principal_name || '')}"></label><label>Phone<input name="phone" value="${esc(data.phone || '')}"></label><label>Email<input name="email" value="${esc(data.email || '')}"></label><label class="span-2">Website<input name="website" value="${esc(data.website || '')}"></label><label class="span-2">Address<input name="address" value="${esc(data.address || '')}"></label><label class="span-2">Report footer<input name="report_footer" value="${esc(data.report_footer || '')}"></label><div class="form-actions span-2"><button class="primary">Save company details</button></div></form>`; shell('Company Details', 'Organisation information used by reports, bills, and certificates', `<section class="panel">${html}</section>`); document.querySelector('#companyForm').onsubmit = async event => { event.preventDefault(); try { await api('/company-profile', { method: 'PUT', body: JSON.stringify(formData(event.target)) }); alert('Company details saved.'); } catch (error) { showError(error); } }; }

async function login() { const form = document.querySelector('#login'); try { const response = await api('/auth/login', { method: 'POST', body: JSON.stringify(formData(form)) }); token = response.token; sessionStorage.token = token; me = response.user; go('dashboard'); } catch (error) { document.querySelector('#error').textContent = error.message; } }
function logout() { api('/auth/logout', { method: 'POST' }).catch(() => {}); sessionStorage.clear(); token = ''; me = null; location.hash = ''; boot(); }
const pages = { dashboard, students, enrollments, bills, attendance, tasks, courses, schools, staff, finance, transfers, reports, company };
async function go(page) { location.hash = page; try { if (!me) me = await api('/auth/me'); await (pages[page] || dashboard)(); } catch (error) { if (/sign in/i.test(error.message)) logout(); else { app.innerHTML = `<div class="error-page"><h1>Unable to open this page</h1><p>${esc(error.message)}</p><button onclick="go('dashboard')">Return to dashboard</button></div>`; } } }
function boot() { if (!token) { app.innerHTML = `<form id="login" class="login"><h1>Expert Learning Hub</h1><p class="muted">Sign in to the web system.</p><p id="error" class="error"></p><div class="form"><label>Username<input name="username" required autofocus></label><label>Password<input type="password" name="password" required></label><button class="primary">Sign in</button></div></form>`; document.querySelector('#login').onsubmit = event => { event.preventDefault(); login(); }; return; } go(location.hash.slice(1) || 'dashboard'); }
Object.assign(window, { go, logout, filterStudents, exportStudentCsv, studentForm, editStudent, archiveStudent, exportEnrollments, enrollmentForm, exportBills, billGenerationForm, billPayment, attendanceAlerts, manualAttendanceForm, switchManualPeople, attendanceReviewForm, exportCourses, courseForm, exportSchools, schoolForm, exportStaff, staffForm, accountForm, moneyForm, taskForm, completeTask, bugForm, transferForm });
boot();
