const app=document.querySelector('#app');let token=sessionStorage.token||'';let lookups={};
const api=async(path,options={})=>{const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}),...(options.headers||{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||'Request failed');return r.status===204?null:r.json()};
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function table(rows,columns){return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${columns.map(c=>`<td>${esc(c[2]?c[2](r):r[c[0]])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${columns.length}" class="muted">No records found.</td></tr>`}</tbody></table></div>`}
function shell(title,body){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">ELH WEB</div>${[['dashboard','Dashboard'],['students','Students'],['enrollments','Enrollments'],['attendance','Attendance Follow-up']].map(([id,label])=>`<button class="nav ${location.hash==='#'+id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}<button class="nav" onclick="logout()">Sign out</button></aside><section class="content"><div class="top"><div><h1>${title}</h1><div class="muted">Expert Learning Hub - browser application</div></div><div class="muted" id="user"></div></div>${body}</section></div>`;api('/auth/me').then(u=>document.querySelector('#user').textContent=`${u.display_name} | ${u.role}`)}
async function dashboard(){const d=await api('/dashboard');shell('Dashboard',`<div class="cards">${[['Students',d.metrics.students],['Active staff',d.metrics.staff],['Active enrollments',d.metrics.enrollments],['Outstanding',d.metrics.outstanding.toLocaleString()]].map(x=>`<div class="card">${x[0]}<b>${x[1]}</b></div>`).join('')}</div><div class="panel"><h2>Punched but not enrolled</h2><p class="muted">Students with attendance activity but no active course.</p>${table(d.punched_not_enrolled,[['student_name','Student'],['class_name','Class'],['contact','Contact'],['punches','Punches'],['last_seen','Last punch']])}</div>`)}
async function students(){const rows=await api('/students');shell('Students',`<div class="toolbar"><input id="search" placeholder="Search students"><select id="status"><option>All</option><option>Active</option><option>Inactive</option></select><button class="primary" onclick="studentForm()">Add student</button></div><div id="studentTable">${table(rows,[['id','ID'],['student_name','Student'],['class_name','Class'],['school_name','School'],['contact','Contact'],['enrolled','Enrolled',r=>r.enrolled?'Yes':'No'],['status','Status']])}</div>`);document.querySelector('#search').oninput=filterStudents;document.querySelector('#status').onchange=filterStudents}
async function filterStudents(){const q=document.querySelector('#search').value,status=document.querySelector('#status').value;const rows=await api(`/students?query=${encodeURIComponent(q)}&status=${status}`);document.querySelector('#studentTable').innerHTML=table(rows,[['id','ID'],['student_name','Student'],['class_name','Class'],['school_name','School'],['contact','Contact'],['enrolled','Enrolled',r=>r.enrolled?'Yes':'No'],['status','Status']])}
async function enrollments(){const rows=await api('/enrollments');shell('Enrollments',`<div class="toolbar"><button class="primary" onclick="enrollmentForm()">Assign enrollment</button></div>${table(rows,[['id','ID'],['student_name','Student'],['course_name','Course'],['level','Level'],['start_date','Start'],['end_date','End'],['monthly_fee','Monthly fee'],['status','Status']])}`)}
async function attendance(){const rows=await api('/attendance/punched-not-enrolled');shell('Attendance Follow-up',`<div class="panel"><h2>Punched but not enrolled</h2><p class="muted">These students should be reviewed and enrolled if appropriate.</p>${table(rows,[['id','ID'],['student_name','Student'],['class_name','Class'],['contact','Contact'],['punches','Punches'],['first_seen','First punch'],['last_seen','Last punch']])}</div>`)}
async function loadLookups(){lookups=await api('/lookups')}
function modal(content){const box=document.createElement('div');box.className='modal';box.innerHTML=`<div class="panel">${content}</div>`;box.onclick=e=>{if(e.target===box)box.remove()};document.body.append(box);return box}
async function studentForm(){await loadLookups();const box=modal(`<h2>Add student</h2><form class="form"><label>Name<input name="name" required></label><label>Class<select name="class_name"><option value="">Not assigned</option>${lookups.classes.map(x=>`<option>${esc(x.level_name)}</option>`).join('')}</select></label><label>School<select name="school_id"><option value="">Not assigned</option>${lookups.schools.map(x=>`<option value="${x.id}">${esc(x.school_name)}</option>`).join('')}</select></label><label>Contact<input name="contact"></label><label>Gender<select name="gender"><option></option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Joining Date (BS)<input name="joining_date" placeholder="2083/05/10" required></label><button class="primary">Save student</button></form>`);box.querySelector('form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.school_id=d.school_id?Number(d.school_id):null;try{await api('/students',{method:'POST',body:JSON.stringify(d)});box.remove();students()}catch(err){alert(err.message)}}}
async function enrollmentForm(){const [students,courses]=await Promise.all([api('/students'),api('/courses')]);const box=modal(`<h2>Assign enrollment</h2><form class="form"><label>Student<select name="student_id">${students.map(x=>`<option value="${x.id}">${esc(x.student_name)}${x.class_name?' - '+esc(x.class_name):''}</option>`).join('')}</select></label><label>Course<select name="course_id">${courses.map(x=>`<option value="${x.id}" data-fee="${x.default_fee||0}">${esc(x.course_name)}</option>`).join('')}</select></label><label>Level / Class<input name="level"></label><label>Start Date (BS)<input name="start_date" placeholder="2083/05/10" required></label><label>End Date (BS)<input name="end_date"></label><label>Monthly Fee<input name="monthly_fee" value="0" type="number" min="0"></label><label>Admission Fee<input name="admission_fee" value="0" type="number" min="0"></label><label>Discount<input name="discount" value="0" type="number" min="0"></label><button class="primary">Save enrollment</button></form>`);const f=box.querySelector('form'),course=f.elements.course_id,fee=f.elements.monthly_fee;course.onchange=()=>fee.value=course.selectedOptions[0].dataset.fee;f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));['student_id','course_id'].forEach(k=>d[k]=Number(d[k]));['monthly_fee','admission_fee','discount'].forEach(k=>d[k]=Number(d[k]));try{await api('/enrollments',{method:'POST',body:JSON.stringify(d)});box.remove();enrollments()}catch(err){alert(err.message)}}}
async function login(){const f=document.querySelector('#login');try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f))) });token=r.token;sessionStorage.token=token;go('dashboard')}catch(e){document.querySelector('#error').textContent=e.message}}
function logout(){sessionStorage.clear();token='';location.hash='';boot()}function go(page){location.hash=page;({dashboard,students,enrollments,attendance}[page]||dashboard)().catch(e=>{if(e.message==='Please sign in.')logout();else app.innerHTML=`<p class="error">${esc(e.message)}</p>`})}function boot(){if(!token){app.innerHTML=`<form id="login" class="login"><h1>Expert Learning Hub</h1><p class="muted">Sign in to the web system.</p><p id="error" class="error"></p><div class="form"><label>Username<input name="username" required autofocus></label><label>Password<input type="password" name="password" required></label><button class="primary">Sign in</button></div></form>`;document.querySelector('#login').onsubmit=e=>{e.preventDefault();login()};return}go(location.hash.slice(1)||'dashboard')}window.go=go;window.logout=logout;window.studentForm=studentForm;window.enrollmentForm=enrollmentForm;boot();
